development:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE", 'dev_secret') %>

test:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE", 'test_secret') %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
